blog/urls.py
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    #path('', index, name='main'),

]

clients/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.apps import ClientsConfig
from clients.views import index, ClientsListView, ClientsCreateView, ClientsUpdateView, ClientsDetailView, \
    ClientsDeleteView, NewTemplateView

app_name = ClientsConfig.name

urlpatterns = [
    path('', index, name='main'),
    path('clients/list/', cache_page(30)(ClientsListView.as_view()), name='clients_list'),
    path('clients/create/', ClientsCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientsUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>', ClientsDetailView.as_view(), name='client_detail'),
    path('client/delete/<int:pk>', ClientsDeleteView.as_view(), name='client_delete'),
    path('create/newsletter/', cache_page(60)(NewTemplateView.as_view()), name='client_new'),

]

config/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls', namespace='clients')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter.views import SettingsListView, SettingsCreateView, SettingsUpdateView, SettingsDeleteView, \
    SettingsDetailView, MessageCreateView, MessageListView, MessageDeleteView, MessageDetailView, MessageUpdateView
from newsletter.apps import NewsletterConfig

app_name = NewsletterConfig.name

urlpatterns = [
    path('list/', cache_page(60)(SettingsListView.as_view()), name='list'),
    path('create/', SettingsCreateView.as_view(), name='create'),
    path('update/<int:pk>/', SettingsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', SettingsDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', SettingsDetailView.as_view(), name='detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/list/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message/detail/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),

]

newsletter/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class MessageSettings(models.Model):
    period_daily = 'daily'
    period_weekly = 'weekly'
    period_monthly = 'monthly'

    period = (
        (period_daily, 'Ежедневно'),
        (period_weekly, 'Раз в неделю'),
        (period_monthly, 'Раз в месяц'),
    )

    status_created = 'created'
    status_started = 'started'
    status_done = 'done'

    status = (
        (status_created, 'Создана'),
        (status_started, 'Запущены'),
        (status_done, 'Завершена'),
    )
    client = models.ForeignKey('clients.Clients', verbose_name='клиент', on_delete=models.CASCADE, **NULLABLE)
    start_time = models.DateTimeField(verbose_name="назначенное время старта расслыки", **NULLABLE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='время рассылки', **NULLABLE)
    periodicity = models.CharField(max_length=20, choices=period, default=period_daily, verbose_name='переодичность')
    status = models.CharField(max_length=20, choices=status, default=status_created, verbose_name='статус')
    message_counter = models.IntegerField(verbose_name='счетчик',default=0)
    day_to_send = models.IntegerField(default=7, verbose_name='Кол-во дней для отправки', **NULLABLE)
    message_id = models.ForeignKey('Message', on_delete=models.CASCADE, verbose_name='message_id', **NULLABLE)
    content_creator = models.CharField(max_length=50, verbose_name='создатель рассылки', **NULLABLE)
    def __str__(self):
        return f'{self.message_id, self.start_time, self.periodicity, self.status}'

    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'


class Message(models.Model):
    client = models.ForeignKey('clients.Clients', on_delete=models.CASCADE, verbose_name='Клиент', **NULLABLE)
    settings = models.ForeignKey('MessageSettings', on_delete=models.CASCADE, verbose_name='Настройка', **NULLABLE)
    message_body = models.TextField(verbose_name='сообщение')
    message_theme = models.CharField(max_length=150, verbose_name='тема сообщения')
    content_creator = models.CharField(max_length=50, verbose_name='создатель текста', **NULLABLE)

    def __str__(self):
        return f'Тема:{self.message_theme} Сообщение:{self.message_body}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

newsletter/forms.py
from django import forms

from newsletter.models import MessageSettings, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NewsletterCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MessageSettings
        exclude = ('status', 'message_counter', 'content_creator')


class MessageCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message

        exclude = ('content_creator', 'settings', 'client')

newsletter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView

from newsletter.forms import NewsletterCreateForm, MessageCreateForm
from newsletter.models import MessageSettings, Message


# Create your views here.
class SettingsListView(LoginRequiredMixin, ListView):
    model = MessageSettings
    template_name = 'newsletter/newsletter_list.html'

    def post(self, request):
        if self.request.method == 'POST':
            for i in MessageSettings.objects.all():
                if i.id == int(self.request.POST.get('pk')):
                    i.status = 'done'
                    i.save()
        return redirect(reverse('newsletter:list'))

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        else:
            queryset = queryset.filter(content_creator=self.request.user.email)
            return queryset


class SettingsCreateView(LoginRequiredMixin, CreateView):
    model = MessageSettings
    template_name = 'newsletter/newsletter_form.html'
    form_class = NewsletterCreateForm
    success_url = reverse_lazy('clients:clients_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.content_creator = self.request.user.email
        self.object.save()
        return super().form_valid(form)


class SettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MessageSettings
    template_name = 'newsletter/newsletter_form.html'
    form_class = NewsletterCreateForm
    success_url = reverse_lazy('newsletter:list')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.is_superuser:
            return self.object
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class SettingsDetailView(LoginRequiredMixin, DetailView):
    model = MessageSettings
    template_name = 'newsletter/newsletter_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.is_staff or self.request.user.is_superuser:
            return self.object
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class SettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MessageSettings
    template_name = 'newsletter/newsletter_confirm_delete.html'
    success_url = reverse_lazy('newsletter:list')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.is_superuser:
            return self.object
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageCreateForm
    template_name = 'newsletter/message_form.html'
    success_url = reverse_lazy('newsletter:message_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.content_creator = self.request.user.email
        self.object.save()
        return super().form_valid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'newsletter/message_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        else:
            queryset = queryset.filter(content_creator=self.request.user)
            return queryset


class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'newsletter.delete_message'
    model = Message
    template_name = 'newsletter/message_confirm_delete.html'
    success_url = reverse_lazy('newsletter:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.is_superuser:
            return self.object
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'newsletter/message_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.is_superuser:
            return self.object
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class MessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'newsletter.change_message'
    model = Message
    template_name = 'newsletter/message_form.html'
    form_class = MessageCreateForm

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.request.user.is_superuser:
            return self.object
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('newsletter:message_detail', args=[self.object.id])

newsletter/templates/newsletter/message_confirm_delete.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление письма</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'clients:main' %}" class="btn btn-success ">Назад</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_detail.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-4 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <div class="row text-center">
                    <div class="col"><h4 class="my-0 font-weight-normal">Просмотр Сообщения</h4></div>
                </div>
            </div>
            <div class="card-body text-center">

                <div class="row-4"><h3>title:{{object.message_theme}} </h3></div>
                <div class="row-4"><h4>text:{{object.message_body}}</h4></div>
                <div class="row-4"><h3>{{object.surname}}</h3></div>


            </div>
            <a href="{% url 'newsletter:message_update' object.pk %}" class="btn btn-success mb-3">Изменить</abutton></a>
            <a href="{% url 'newsletter:message_list'  %}" class="btn btn-success mb-3">Назад</abutton></a>
            <a href="{% url 'newsletter:message_delete' object.id %}" class="btn btn-danger">Удалить</abutton></a>

        </div>

    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_form.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-4">
    <div class="col-1"></div>
    <div class="col-4">
        <form method="post" action="" class="form-floating" enctype="multipart/form-data">
            <div class="card">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Добавить сообщение </h4>
                </div>
                <div class="card-body text-center">

                    {% csrf_token %}
                    {{form.as_p}}
                    {% if object %}
                    <button type="submit" class="btn btn-danger">Изменить</button>
                    {% else %}
                    <button type="submit" class="btn btn-danger">Создать</button>
                    {% endif %}
                    <a href="{% url 'newsletter:message_list' %}" class="btn btn-success">Назад</a>

                </div>
            </div>
        </form>
    </div>
    <div class="col-1"></div>

    </div>
</div>
</div>

{% endblock %}

newsletter/templates/newsletter/message_list.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-3">
    <div class="col-12 text-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body float-center">
                <h5 class="card-title">Сохраненные сообщения</h5>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-1"></div>
    <div class="col-2 text-center">
        <a href="{% url 'newsletter:message_create' %}" class="btn btn-success">написать новое сообщение сообщение</a>
    </div>
</div>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Тема</th>
            <th scope="col">ID</th>
            <th scope="col">Текст</th>
            <th scope="col">Создатель</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <div class="col-12">
            <tr>
                <td><a href="{% url 'newsletter:message_update' object.pk %}" class="btn btn-success">Изменить </a>
                    {% if user.is_staff%}
                    {% else %}
                    <a href="{% url 'newsletter:message_delete' object.id %}" class="btn btn-danger">Удалить </a>
                    {% endif %}
                    {% if user.is_superuser%}
                    <a href="{% url 'newsletter:message_delete' object.id %}" class="btn btn-danger">Удалить </a>
                </td>
                {% endif %}
                <th>
                    <h5>{{object.message_theme}}</a></h5>
                </th>
                <td><a href="{% url 'newsletter:message_detail' object.pk%}"><h5>{{object.id}}</h5></a></td>

                <td><h5>{{object.message_body|slice:20}}</h5></td>
                <td><h5>{{object.content_creator|default:'БОГ'}}</h5></td>
            </tr>
        </div>
        </tbody>

        {% endfor %}
    </table>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_confirm_delete.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление настройки для {{object.client.email}}</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'newsletter:list' %}" class="btn btn-success ">Назад</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_detail.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-4 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <div class="row text-center">
                    <div class="col"><h4 class="my-0 font-weight-normal">Просмотр рассылки</h4></div>

                </div>
            </div>
            <div class="card-body text-center">
                <div class="row-4"><h3>была создана для {{object.client.email}} </h3></div>
                {% if object.start_time%}
                <div class="row-4"><h2>{{object.start_time}} </h2></div>
                {% else %}
                <div class="row-4"><h2>{{object.created_time}} </h2></div>
                {%endif%}
                <div class="row-4"><h3>переодичность: {{object.periodicity}}</h3></div>
                <div class="row-4"><h3>статус: {{object.status}}</h3></div>
                <div class="row-4"><h3>заложено дней для отправки: {{object.day_to_send}}</h3></div>
                <div class="row-4"><h3>тема сообщения была:{{object.message_id.message_theme}}</h3></div>
                <div class="row-4"><h3>создал: {{object.content_creator}}</h3></div>

            </div>
            <a href="{% url 'newsletter:update' object.pk %}" class="btn btn-success mb-3">Изменить</abutton></a>
            <a href="{% url 'newsletter:list' %}" class="btn btn-success mb-3">Назад</abutton></a>
            <a href="{% url 'newsletter:delete' object.id %}" class="btn btn-danger">Удалить</abutton></a>

        </div>

    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_form.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-4">
    <div class="col-1"></div>
    <div class="col-4">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Добавление настройкy сообщений</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    {% if object %}
                    <button type="submit" class="btn btn-danger">Изменить</button>
                    {% else %}
                    <button type="submit" class="btn btn-danger">Создать</button>
                    {% endif %}
                    <a href="{% url 'newsletter:list' %}" class="btn btn-success">Назад</a>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

newsletter/templates/newsletter/newsletter_list.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-3" xmlns="http://www.w3.org/1999/html">
    <div class="col-12 text-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body float-center">
                <h5 class="card-title">Сохраненные настройки</h5>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-1"></div>
    <div class="col-2 text-center">
        <a href="{% url 'newsletter:create' %}" class="btn btn-success">Добавить настройку</a>
    </div>
</div>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Клиент</th>
            <th scope="col">Время старта</th>
            <th scope="col">Переодичность</th>
            <th scope="col">Статус</th>
            <th scope="col">Создатель</th>


        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <div class="col-12">
            <tr>

                {% if user.is_staff and not user.is_superuser%}
                {% csrf_token %}
                <td>
                    <form method="post" action="" class="form-floating">
                        <button class="btn btn-warning" type="submit" name="pk" value="{{object.pk}}">Отключить</button>
                    </form>
                </td>
                {% endif %}
                {% if not user.is_staff %}
                <td>
                    <div class="row">
                        <a href="{% url 'newsletter:update' object.id %}" class="btn btn-success">изменить </a>
                        <a href="{% url 'newsletter:delete' object.id %}" class="btn btn-danger">Удалить </a>
                    </div>
                </td>
                {% endif %}
                {% if user.is_superuser %}
                <td>
                    <div class="row">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <button class="btn btn-warning" type="submit" name="pk" value="{{object.pk}}">Отключить
                            </button>
                        </form>
                        <a href="{% url 'newsletter:update' object.id %}" class="btn btn-success">изменить </a>
                        <a href="{% url 'newsletter:delete' object.id %}" class="btn btn-danger">Удалить </a>
                        <a href="{% url 'newsletter:detail' object.id %}" class="btn btn-success">Просмотр </a>
                    </div>
                </td>
                {% endif %}

                <th><h5>{{object.client.email}}</a></h5></th>
                {% if object.start_time %}
                <th><h5>{{object.start_time}}</a></h5></th>
                {% else %}
                <th><h5>{{object.created_time}}</a></h5></th>
                {% endif %}
                <th><h5>{{object.periodicity}}</a></h5></th>
                <th><h5>{{object.status}}</a></h5></th>
                <td><h5>{{object.content_creator|default:'БОГ'}}</h5></td>

            </tr>
        </div>
        </tbody>

        {% endfor %}
    </table>
</div>
{% endblock %}