blog/urls.py
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    #path('', index, name='main'),

]

clients/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.apps import ClientsConfig
from clients.views import index, ClientsListView, ClientsCreateView, ClientsUpdateView, ClientsDetailView, \
    ClientsDeleteView, NewTemplateView

app_name = ClientsConfig.name

urlpatterns = [
    path('', index, name='main'),
    path('clients/list/', cache_page(30)(ClientsListView.as_view()), name='clients_list'),
    path('clients/create/', ClientsCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientsUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>', ClientsDetailView.as_view(), name='client_detail'),
    path('client/delete/<int:pk>', ClientsDeleteView.as_view(), name='client_delete'),
    path('create/newsletter/', cache_page(60)(NewTemplateView.as_view()), name='client_new'),

]

config/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls', namespace='clients')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LIView, LOView, RegisterView, verification, genpass, UserUpdateView, UserListView, \
    UserDeleteView, user_deactivate, user_activate

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LIView.as_view(), name='login'),
    path('logout/', LOView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/<int:pk>/', verification, name='verification'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('update/genpass', genpass, name='genpass'),
    path('users/list', UserListView.as_view(), name='list'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='delete'),
    path('deactivate/<int:pk>/', user_deactivate, name='deactivate'),
    path('activate/<int:pk>/', user_activate, name='activate'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from clients.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='email')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone_number = models.CharField(max_length=50, verbose_name='номер телефона', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='активность')
    is_staff = models.BooleanField(default=False, verbose_name='модератор')
    country = models.CharField(max_length=20, verbose_name='страна',**NULLABLE)
    verification = models.IntegerField(verbose_name='ключ верификации', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    # class Meta:
    #     verbose_name = 'Пользователь'
    #     verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from clients.forms import StyleFormMixin
from users.models import User


class UserForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'phone_number', 'country', 'password1', 'password2', 'avatar')


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'phone_number', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import time

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from config import settings
from services.message import mail
from users.forms import UserForm, UserUpdateForm
from users.models import User


# Create your views here.
class LIView(LoginView):
    template_name = 'users/login.html'


class LOView(LogoutView):
    template_name = 'users/logout.html'


class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        verification = random.randint(100000, 999999)
        new_user = form.save()
        mail(message=f'http://127.0.0.1:8000/users/verification/{verification}', title='Верификация',
             client=new_user.email)
        new_user.verification = verification
        new_user.save()
        return super().form_valid(form)


def verification(request, pk):
    for i in User.objects.all():
        if i.verification == pk and i.email == User.objects.get(verification=pk).email:
            i.is_active = True
            i.save()
    return render(request, 'users/verification.html')


@login_required
@permission_required('users.change_user')
def user_deactivate(request, pk):
    for i in User.objects.all():
        if i.id == pk:
            i.is_active = False
            i.save()
    return redirect(reverse('users:list'))


def user_activate(request, pk):
    for i in User.objects.all():
        if i.id == pk:
            i.is_active = True
            i.save()

    return redirect(reverse('users:list'))


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:update')
    form_class = UserUpdateForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data

    def get_object(self, queryset=None):
        return self.request.user


def genpass(request):
    password = str(random.randint(0, 999999))
    request.user.set_password(password)
    request.user.save()
    mail(password)
    send_mail(message=password, title='Генерация пароля', client=request.user.email)

    return redirect(reverse('users:login'))


class UserListView(ListView):
    model = User

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff or self.request.user.is_superuser:
            return queryset
        else:
            return Http404

    def get_context_data(self, *, object_list=None, **kwargs):
        return super().get_context_data(**kwargs)

    def post(self, request):
        if self.request.method == 'POST':
            for i in User.objects.all():
                if i.email == self.request.POST.get('name'):
                    i.is_staff = True
                    i.save()
        return redirect(reverse('users:list'))

    template_name = 'users/users_list.html'


class UserDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'users.del_user'
    model = User
    template_name = 'users/users_confirm_delete.html'
    success_url = reverse_lazy('users:list')

users/templates/users/login.html
{% extends 'clients/base.html' %}
{%block content%}
<div class="row">
<div class="col-4 text-center"></div>

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Вход в сервис</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Войти</button>

                </form>
            </div>
        </div>
    </div>

    </div>
{%endblock%}

users/templates/users/logout.html
{% extends 'clients/base.html' %}
{%block content%}
{%endblock%}

users/templates/users/register.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row">
<div class="col-4"></div>
<div class="col-6 text-center">

    <div class="col-lg-8 col-md-3 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Регистрация</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Создать</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row">
<div class="col-4"></div>
<div class="col-6 text-center">

    <div class="col-lg-8 col-md-3 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Информация {{object.email}}</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Сохранить</button>
                    <a href="{% url 'clients:main' %}" class="btn btn-success">Назад</a>
                </form>
            </div>
            <div class="card-footer text-center">
                <a href="{% url 'users:genpass' %}" class="btn btn-danger">Генерация пароля</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/users_confirm_delete.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление пользователя {{object.email}}</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'users:list' %}" class="btn btn-success ">Назад</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-3"></div>
<div class="row mb-3">
    <div class="col-12 text-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body float-center">
                <h5 class="card-title">Клиенты сервиса</h5>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">

<div class="col-2">
    <div class="card-body">
        <form method="post" action="" class="form-floating">
            {% csrf_token %}
            <div class="mb-3">
                <label for="name">добавить права модератора</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="email" required>
            </div>
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Добавить</button>
        </form>
    </div>
</div>


</div>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">E-mail</th>
            <th scope="col">Id</th>
            <th scope="col">Активный</th>
            <th scope="col">Модерация</th>
            <th scope="col">Права администратора</th>

        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <div class="col-12">
            <tr>
                <td><a href="{% url 'users:deactivate' object.pk %}" class="btn btn-success"> Бан </a>
                    <a href="{% url 'users:activate' object.pk %}" class="btn btn-success"> Активировать </a>
                    {% if user.is_superuser %}
                    <a href="{% url 'users:delete' object.pk %}" class="btn btn-danger">Удалить </a></td>
                {% endif %}
                <td><h5>{{object.email}}</h5></td>
                <td><h5>{{object.id}}</h5></td>
                <td><h5>{{object.is_active}}</h5></td>
                <td><h5>{{object.is_staff}}</h5></td>
                <td><h5>{{object.is_superuser}}</h5></td>

            </tr>
        </div>
        </tbody>

        {% endfor %}
    </table>
</div>
{% endblock %}

users/templates/users/verification.html
{% extends 'clients/base.html' %}
{%block content%}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1>Вы успешно подтвердили регистрацию</h1>
    </div>

</div>
{%endblock%}