blog/urls.py
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    #path('', index, name='main'),

]

clients/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.apps import ClientsConfig
from clients.views import index, ClientsListView, ClientsCreateView, ClientsUpdateView, ClientsDetailView, \
    ClientsDeleteView, NewTemplateView

app_name = ClientsConfig.name

urlpatterns = [
    path('', index, name='main'),
    path('clients/list/', cache_page(30)(ClientsListView.as_view()), name='clients_list'),
    path('clients/create/', ClientsCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientsUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>', ClientsDetailView.as_view(), name='client_detail'),
    path('client/delete/<int:pk>', ClientsDeleteView.as_view(), name='client_delete'),
    path('create/newsletter/', cache_page(60)(NewTemplateView.as_view()), name='client_new'),

]

config/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls', namespace='clients')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

logs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from logs.views import LogsListView, LogsDetailView, LogsDeleteView
from logs.apps import LogsConfig

app_name = LogsConfig.name

urlpatterns = [
    path('list/', cache_page(60)(LogsListView.as_view()), name='list'),
    path('detail/<int:pk>/', LogsDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', LogsDeleteView.as_view(), name='delete'),

]

newsletter/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter.views import SettingsListView, SettingsCreateView, SettingsUpdateView, SettingsDeleteView, \
    SettingsDetailView, MessageCreateView, MessageListView, MessageDeleteView, MessageDetailView, MessageUpdateView
from newsletter.apps import NewsletterConfig

app_name = NewsletterConfig.name

urlpatterns = [
    path('list/', cache_page(60)(SettingsListView.as_view()), name='list'),
    path('create/', SettingsCreateView.as_view(), name='create'),
    path('update/<int:pk>/', SettingsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', SettingsDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', SettingsDetailView.as_view(), name='detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/list/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message/detail/<int:pk>', MessageDetailView.as_view(), name='message_detail'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),

]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LIView, LOView, RegisterView, verification, genpass, UserUpdateView, UserListView, \
    UserDeleteView, user_deactivate, user_activate

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LIView.as_view(), name='login'),
    path('logout/', LOView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verification/<int:pk>/', verification, name='verification'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('update/genpass', genpass, name='genpass'),
    path('users/list', UserListView.as_view(), name='list'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='delete'),
    path('deactivate/<int:pk>/', user_deactivate, name='deactivate'),
    path('activate/<int:pk>/', user_activate, name='activate'),

]

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='заголовок')
    text_body = models.TextField(verbose_name='содержание статьт')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    count_of_views = models.IntegerField(default=0, verbose_name="количество просмотров", **NULLABLE)
    publication_date = models.DateTimeField(auto_created=True, verbose_name="дата публикации", **NULLABLE)

    def __str__(self):
        return f'{self.title, self.count_of_views}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

clients/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Clients(models.Model):
    email = models.CharField(max_length=150, verbose_name='емейл')
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    surname = models.CharField(max_length=100, verbose_name='отчество')
    comments = models.TextField(verbose_name='комментарии')
    content_creator = models.EmailField(max_length=50, verbose_name='создатель клиента', **NULLABLE)

    def __str__(self):
        return f'{self.email},{self.last_name}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

clients/forms.py
from django import forms

from clients.models import Clients


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientsCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Clients
        exclude = ('content_creator',)

clients/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView

from blog.models import Blog
from clients.forms import ClientsCreateForm
from clients.models import Clients
from newsletter.models import MessageSettings
from services.permissions import get_permissions
from users.models import User


# Create your views here.

def index(request):
    if request.method == "GET":
        get_permissions(request)
    list = [i for i in Blog.objects.all()]
    random.shuffle(list)
    context = {
        'count_of_newsletter': len([i for i in MessageSettings.objects.all()]),
        'active_news': len([i for i in MessageSettings.objects.filter(status='started')]),
        'uniq_clients': len({i.email for i in Clients.objects.all()}),
        'blog_list': list[:3]
    }

    return render(request, 'clients/main.html', context)


class ClientsListView(LoginRequiredMixin, ListView):
    model = Clients

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        else:
            queryset = queryset.filter(content_creator=self.request.user)
            return queryset


class ClientsCreateView(LoginRequiredMixin, CreateView):
    model = Clients
    form_class = ClientsCreateForm
    success_url = reverse_lazy('clients:clients_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.content_creator = self.request.user.email
        self.object.save()
        return super().form_valid(form)


class ClientsUpdateView(LoginRequiredMixin, UpdateView):
    model = Clients
    form_class = ClientsCreateForm
    success_url = reverse_lazy('clients:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('clients:client_detail', args=[self.object.id])


class ClientsDetailView(LoginRequiredMixin, DetailView):
    model = Clients
    form_class = ClientsCreateForm
    success_url = reverse_lazy('clients:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if not self.request.user.is_staff and self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class ClientsDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'clients.delete_clients'
    model = Clients
    success_url = reverse_lazy('clients:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object()
        if self.object.content_creator != self.request.user.email:
            raise Http404
        return self.object


class NewTemplateView(TemplateView):
    template_name = 'clients/create_newsletter.html'

clients/templates/clients/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DjangoProject</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/offcanvas.css' %}" rel="stylesheet">
</head>

<body class="bg-light">

<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'clients:main'%}">"Сервис рассылок"</a>
    <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'clients:main'%}">Главная <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:logout'%}"> Выход <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:update' user.pk %}">Профиль</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:login'%}">Вход <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register'%}">Регистрация</a>
            </li>
            {% endif %}
        </ul>

            <div class="text-success my-2 my-sm-0" type="text">Здесь могла быть ваша реклама :)))</div>

        </ul>

        </ul>
        <!--        <form class="form-inline my-2 my-lg-0">-->
        <!--            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
        <!--            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--        </form>-->
    </div>
</nav>

<div class="nav-scroller bg-white box-shadow">
    {% if user.is_authenticated %}
    <nav class="nav nav-underline">
        <a class="nav-link active" href="{% url 'clients:client_new' %}">Создать рассылку</a>
        <a class="nav-link active" href="{% url 'clients:clients_list' %}">К вашим пользователям</a>
        <a class="nav-link active" href="{% url 'newsletter:list' %}">К вашим рассылкам</a>
        <a class="nav-link active" href="{% url 'newsletter:message_list' %}">К вашим сообщениям</a>
        {% if user.is_staff or user.is_superuser %}
        <a class="nav-link active" href="{% url 'logs:list' %}">К логам</a>
        {% endif %}
        {% if user.is_staff %}
        <a class="nav-link active" href="{% url 'users:list' %}">Список пользователей</a>
        {% endif %}
    </nav>
    {% else %}
    <div class="col mb-1"></div>
    <div class="col ">
        <h5>Войдите или зарегистрируйтесь</h5>
    </div>
    {% endif %}
</div>
{% block content %}
{% endblock %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js'%}"></script>
<script src="{% static 'offcanvas.js'%}"></script>
</body>
</html>

clients/templates/clients/clients_confirm_delete.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление клиента {{object.email}}</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'clients:clients_list' %}" class="btn btn-success ">Назад</abutton></a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/clients_detail.html
{% extends 'clients/base.html' %}
{% block content %}

<div class="row">
    <div class="col-1"></div>

    <div class="col-lg-4 col-md-4 col-sm-12">
        <div class="card">
            <div class="card-header">
                <div class="row text-center">
                    <div class="col"><h4 class="my-0 font-weight-normal">Просмотр клиента {{object.email }}</h4></div>

                </div>
            </div>
            <div class="card-body text-center">
                <div class="row-4"><h4>фамилия: {{object.last_name}} </h4></div>
                <div class="row-4"><h4>имя: {{object.first_name}} </h4></div>
                <div class="row-4"><h4>отчество: {{object.surname}}</h4></div>
                <div class="row-4"><h4>комментарий: {{object.comments}}</h4></div>


            </div>
            <a href="{% url 'clients:client_update' object.pk %}"
               class="btn btn-success mb-1">Изменить</abutton></a>
            <a href="{% url 'clients:clients_list'  %}" class="btn btn-success mb-1">Назад</abutton></a>
            <a href="{% url 'clients:client_delete' object.id %}" class="btn btn-danger">Удалить</abutton></a>

        </div>

    </div>
    <div class="col-1"></div>
    <div class="col-4">
        {% for obj in object.message_set.all %}
        <div class="card mb-2">
            <div class="card-header">
                <div class="row text-center">
                    <div class="col-8"><h4 class="my-0 font-weight-normal">Сообщение клиента</h4></div>
                    <div class="col-2">

                        <a href="{% url 'newsletter:create'%}" class="btn btn-success">Добавить
                            сообщение</a>
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <div class="row-4"><h5>ID {{obj.id}} </h5></div>
                <div class="row-4"><h4>статус:"{{obj.settings.status}}" </h4></div>
                <div class="row-4"><h4>переодичность:"{{obj.settings.periodicity}}" </h4></div>
                <div class="row-4"><h5>Тема:{{obj.message_theme}} </h5></div>

                <div class="row-4"><h5>Сообщение:{{obj.message_body}}</h5></div>


            </div>
            <a href="{% url 'newsletter:message_update' obj.pk %}"
               class="btn btn-success mb-1">Изменить</abutton></a>
            <a href="{% url 'newsletter:message_delete' object.id %}" class="btn btn-danger">Удалить</abutton></a>

        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

clients/templates/clients/clients_form.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Добавление Клиента</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    {% if object %}
                    <button type="submit" class="btn btn-danger">Изменить</button>
                    <a href="{% url 'newsletter:list' %}" class="btn btn-success">Назад</a>
                    {% else %}
                    <button type="submit" class="btn btn-danger">Создать</button>
                    {% endif %}

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/clients_list.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-3">
    <div class="col-12 text-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body float-center">
                <h5 class="card-title">Клиенты сервиса</h5>
            </div>
        </div>
    </div>
</div>
<div class="row mb-3">
    <div class="col-1"></div>
    <div class="col-2 text-center">
        <a href="{% url 'clients:client_create' %}" class="btn btn-success">Добавить клиента</a>
    </div>
</div>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Фио</th>
            <th scope="col">E-mail</th>
            <th scope="col">количество рассылок</th>

        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <div class="col-12">
            <tr>
                <td><a href="{% url 'clients:client_update' object.pk %}" class="btn btn-success">Изменить </a>
                    <a href="{% url 'clients:client_delete' object.pk %}" class="btn btn-danger">Удалить </a></td>

                <th>
                    <h5><a href="{% url 'clients:client_detail' object.pk %}"> {{object.last_name}}
                        {{object.first_name}} {{object.surname}}</a></h5>
                </th>

                <td><h5>{{object.email}}</h5></td>
                <td>{{object.messagesettings_set.all|length}}</td>


            </tr>
        </div>
        </tbody>

        {% endfor %}
    </table>
</div>
{% endblock %}

clients/templates/clients/create_newsletter.html
{% extends 'clients/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row mb-4">
    <div class="col-2">

    </div>
    <div class="col-4">
        <div class="card">
            <div class="card-header text-center">
                <h2>
                    <div class="text-danger">Как создать рассылку </div>
                </h2>
            </div>
            <div class="card-body">
                <h4> Step 1 : <a href="{% url 'clients:client_create' %}"> Добавляем клиента </a></h4>
                <p>
                    ------------------------------------------------------------------------------------------------------------</p>
                <h4> Step 2 : <a href="{% url 'clients:client_create' %}"> Пишем для него сообщение </a></h4> </h4>
                <p>
                    ------------------------------------------------------------------------------------------------------------</p>
                <h4> Step 3 : <a href="{% url 'clients:client_create' %}"> Указываем в настройках - клиент и
                    сообщение </a></h4></h4>
                <p>
                    ------------------------------------------------------------------------------------------------------------</p>
            </div>
            <div class="coed-footer text-center">
                <h3>Готово! ваша рассылка добавлена :)</h3>
                <h5>проверка готовности к отправке каждые 5 минут.</h5>
                <h3>Статус можно посмотреть во вкладке "К вашим рассылкам"</h3>
                <h4>created - ждет отправки<p></p> started - отправка, согласно времени <p></p> done - закончилась , продлевать будете ?)</h4>
                <div class="row mb-4"></div>
            </div>
        </div>
    </div>
</div>


</body>
</html>
{% endblock content %}

clients/templates/clients/main.html
{% extends 'clients/base.html' %}
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">

        <div class="lh-100">
            <h6 class="mb-0 text-white lh-100">Пурпурный</h6>
            <small>с 2011</small>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        {% for obj in blog_list %}
        <h6 class="border-bottom border-gray pb-2 mb-0">{{ obj.publication_date }}</h6>
        <div class="media text-muted pt-3">
            <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
            <p class="media-body pb-3 mb-2 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{obj.title}}</strong>
                {{obj.text_body|slice:50}}
            </p>
        </div>
        {% endfor %}

        <small class="d-block text-right mt-3">
            <a href="#">All updates</a>
        </small>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-danger pb-2 mb-0">Статистика:</h6>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-danger">
                <strong class="d-block text-gray-dark">Количество рассылок:</strong>
            <p></p>
            {{count_of_newsletter}}
            </p>

        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-danger">
                <strong class="d-block text-gray-dark">Количество активных рассылок:</strong>
            <p></p>
            {{active_news}}
            </p>

        </div>
                <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-danger">
                <strong class="d-block text-gray-dark">Количество уникальных клиентов:</strong>
            <p></p>
            {{uniq_clients}}
            </p>

        </div>

    </div>
</main>
{% endblock %}