blog/urls.py
from blog.apps import BlogConfig

app_name = BlogConfig.name


urlpatterns = [
    #path('', index, name='main'),

]

clients/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from clients.apps import ClientsConfig
from clients.views import index, ClientsListView, ClientsCreateView, ClientsUpdateView, ClientsDetailView, \
    ClientsDeleteView, NewTemplateView

app_name = ClientsConfig.name

urlpatterns = [
    path('', index, name='main'),
    path('clients/list/', cache_page(30)(ClientsListView.as_view()), name='clients_list'),
    path('clients/create/', ClientsCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>', ClientsUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>', ClientsDetailView.as_view(), name='client_detail'),
    path('client/delete/<int:pk>', ClientsDeleteView.as_view(), name='client_delete'),
    path('create/newsletter/', cache_page(60)(NewTemplateView.as_view()), name='client_new'),

]

config/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls', namespace='clients')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

logs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from logs.views import LogsListView, LogsDetailView, LogsDeleteView
from logs.apps import LogsConfig

app_name = LogsConfig.name

urlpatterns = [
    path('list/', cache_page(60)(LogsListView.as_view()), name='list'),
    path('detail/<int:pk>/', LogsDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', LogsDeleteView.as_view(), name='delete'),

]

logs/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Create your models here.
class Logs(models.Model):
    newsletter = models.ForeignKey('newsletter.MessageSettings', on_delete=models.SET_NULL,
                                   verbose_name='рассылка', **NULLABLE)
    time = models.DateTimeField(auto_now_add=True, verbose_name="время попытки")
    status = models.BooleanField(default=False, verbose_name='статус попытки', **NULLABLE)
    answer = models.TextField(verbose_name="ответ сервиса", **NULLABLE)

    def __str__(self):
        return f"logs:status {self.status}, newsletter {self.newsletter} "

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView

from logs.models import Logs


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs
    def get_queryset(self):
        if self.request.user.is_staff or self.request.user.is_superuser:
            return super().get_queryset()
        else:
            raise Http404


class LogsDetailView(LoginRequiredMixin, DetailView):
    model = Logs


class LogsDeleteView(LoginRequiredMixin, DeleteView):
    model = Logs
    success_url = reverse_lazy('logs:list')

logs/templates/logs/logs_confirm_delete.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление письма</h4>
            </div>
            <div class="card-body text-center">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                    <a href="{% url 'clients:main' %}" class="btn btn-success ">Назад</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

logs/templates/logs/logs_detail.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="col-12 text-center">

    <div class="col-lg-4 col-md-4 col-sm-12">
        <div class="card mb-4 box-shadow ">
            <div class="card-header">
                <div class="row text-center">
                <div class="col-8"> <h4 class="my-0 font-weight-normal">Просмотр клиента</h4></div>
                <div class="col-2">

                        <a href="{% url 'newsletter:newsletter_create' object.pk%}" class="btn btn-success">Добавить рассылку</a>
                </div>
                    </div>
            </div>
            <div class="card-body text-center">
                <div class="row-4"><h2>{{object.email}} </h2></div>
                <div class="row-4"><h2>{{object.first_name}} </h2></div>
                <div class="row-4"><h3>{{object.last_name}}</h3></div>
                <img class="bd-placeholder-img card-img-center" width="40%" height="180%" src="/media/{{object.image}}" alt="#">
                <h3>-----------------------</h3>
                <h2><div class="row-4"> цена: {{object.purchase_price}}</div></h2>


            </div>
            <a href="{% url 'clients:client_update' object.pk %}" class="btn btn-success mb-3">Изменить</abutton></a>
            <a href="{% url 'clients:clients_list'  %}" class="btn btn-success mb-3">Назад</abutton></a>
            <a href="{% url 'clients:client_delete' object.id %}" class="btn btn-danger">Удалить</abutton></a>

        </div>

    </div>
</div>
{% endblock %}

logs/templates/logs/logs_list.html
{% extends 'clients/base.html' %}
{% block content %}
<div class="row mb-3">
    <div class="col-12 text-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body float-center">
                <h5 class="card-title">Логи</h5>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">клиент</th>
            <th scope="col">переодичность</th>
            <th scope="col">статус рассылки</th>
            <th scope="col">время попытки</th>
            <th scope="col">статсу попытки</th>
            <th scope="col">ответ сервера</th>

        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <div class="col-12">
            <tr>

                <td>{{object.newsletter.client.email}}
                <td>{{object.newsletter.periodicity}}</td>
                <td>{{object.newsletter.status}}</td>
                <td>{{object.time}}</td>
                <td>{{object.status}}</td>
                {% if object.answer > 0 %}
                <td>good</td>
                {% else %}
                <td>good</td>
                {%endif%}
            </tr>
        </div>
        </tbody>

        {% endfor %}
    </table>
</div>
{% endblock %}